package com.example.meditationbio.ui

enum class AppScreen {
    HOME,
    PROBLEM_FIELDS,
    RECOMMENDATIONS,
    RECOMMENDATION_DETAIL,
    PRE_SESSION_QUESTIONNAIRE,
    PRE_BLOOD_PRESSURE,
    MEDITATION_SESSION,
    POST_BLOOD_PRESSURE,
    POST_SESSION_QUESTIONNAIRE,
    SESSION_RESULT,
    PROGRESS,
    PROFILE,
    EDITOR
}